name: andromeda
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.1+1

environment:
  #sdk: '>=2.19.6 <3.0.0'
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_rating_bar: ^4.0.1
  html_parsed_read_more: ^0.0.1
  #flutter_custom_clippers: ^2.1.0
  http: ^1.2.2
  geolocator: ^12.0.0
  path_provider: ^2.1.4
  sqflite: ^2.3.3+1
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  carousel_slider: ^5.0.0
  readmore: ^3.0.0
  google_maps_flutter: ^2.8.0
  multi_select_flutter: ^4.1.3
  ftoast: ^2.0.0
  panara_dialogs: ^0.1.5
  shimmer: ^3.0.0
  camera: ^0.11.0+2
  path: ^1.9.0
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  flutter_background_service: ^5.0.7
  flutter_local_notifications: ^17.1.1+2
  socket_io_client: ^2.0.3+1
  device_info_plus: ^10.1.1
  location: ^7.0.0
  geocoding: ^3.0.0
  permission_handler: ^11.3.1
  #fluttertoast: ^8.2.6
  #html: ^0.15.4


dev_dependencies:
  flutter_test:
    sdk: flutter
    
 # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/Back.png
    - assets/Black.jpg
    - assets/IniciarSesionCliente.png
    - assets/IniciarSesionRest.png
    - assets/Login.png
    - assets/notFoundImg.png
    - assets/Profile.png
    - assets/Masculino.jpg
    - assets/Femenino.jpg
    - assets/LogoBlack.png
    - assets/Connection_Lost.png
    - assets/no_search_result.png
    - assets/LogoWhite.png
    - .env

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-package